[package]
name = "actix-mqtt-client"
version = "0.1.2"
authors = ["Syndim <im@syndim.org>"]
edition = "2018"
repository = "https://github.com/Syndim/actix-mqtt-client"
description = "A MQTT client based on the actix framework"
license = "MIT"

[dependencies]
actix = "0.8"
mqtt-protocol = "0.7"
log = "0.4"
futures = "0.1"
tokio = "0.1"
lazy_static = "1.4"
rand = "0.7"

[dev-dependencies]
env_logger = "0.6"
rand = "0.7"